/* do not change the next line, which is the DataSource: 
Movex Java
*/ 

	SELECT MLBANO,MLITNO,MLWHSL,MLCAMU, SUM(MLSTQT) AS STQT 
	FROM ##MITLOC##
	WHERE  MLCONO=%cono%  AND MLWHLO='%whlo%'  and MLWHSL='%whsl%'
	GROUP BY MLBANO,MLITNO,MLWHSL,MLCAMU ORDER BY MLITNO,MLWHSL,MLCAMU