/* do not change the next line, which is the DataSource: 
Movex Java
*/ 
	SELECT A.MQRIDN
		,A.MQRIDL
		,A.MQITNO
		,A.MQBANO
		,A.MQCAMU
		,A.MQWHSL
		,A.MQTWSL
		,A.MQPLRN
		,A.MQSOFT
		,MM.MMDCCD
		,MM.MMITDS
		,cast(A.MQTRQT as numeric(17,0)) MQTRQT
		,cast(A.MQTRQT as numeric(17,2)) MQTRQT2D
		,A.MQALQT
		,SUM(B.O0DLQT) PACKED
		,A.MQTRQT - SUM(B.O0DLQT) TOPACK
		,MAX(B.O0PANR) PACKNR
		,G2STAT,
		cast(coalesce(G2ALQT,0) as numeric(17,0)) G2DLQT ,
		cast(coalesce(G2ALQT,0) as numeric(17,2)) G2DLQT2D ,
		G2MSLN,
		ML.STQT,ML.ALQT
	FROM ##MITALO## A
	LEFT JOIN ##MFTRND## B ON B.O0CONO = A.MQCONO
		AND B.O0WHLO = A.MQWHLO
		AND B.O0DLIX = A.MQRIDI
		AND B.O0RIDN = A.MQRIDN
		AND B.O0RIDL = A.MQRIDL
		AND B.O0BANO = A.MQBANO
		AND B.O0CAMU = A.MQCAMU
		AND B.O0PLRN = A.MQPLRN
	INNER JOIN ##MITMAS## MM ON MM.MMCONO = A.MQCONO
		AND MM.MMITNO = A.MQITNO
		
		left join ##MHILIN## on G2CONO=A.MQCONO 
		and G2MSGN='%msgn%'
		and G2WHLO=A.MQWHLO
		and G2DLIX=A.MQRIDI
		and G2WHSL=A.MQWHSL
		and G2ITNO=A.MQITNO
		and G2BANO=A.MQBANO	
		and G2RIDN=A.MQRIDN
		and G2RIDL=A.MQRIDL
		and G2STAT<90
		
	join (select MLCONO,MLWHLO,MLITNO,MLWHSL,cast(sum(MLSTQT/*+MLALQT rem 1.12.20*/) as numeric(17,2)) STQT, cast(sum(MLALQT) as numeric(17,2)) ALQT 
	from ##MITLOC## group by MLCONO,MLWHLO,MLITNO,MLWHSL) as ML 
	on  ML.MLCONO=A.MQCONO
	and ML.MLWHLO=A.MQWHLO
	and ML.MLITNO=A.MQITNO
	and ML.MLWHSL=A.MQWHSL
	
	WHERE A.MQCONO = %cono%
		AND A.MQWHLO = '%whlo%'
		AND A.MQRIDI = %ridi%
		AND A.MQPLSX = %plsx%
		AND A.MQSTAT < 70
	GROUP BY A.MQRIDN
		,A.MQRIDL
		,A.MQITNO
		,A.MQBANO
		,A.MQCAMU
		,A.MQWHSL
		,A.MQTWSL
		,A.MQPLRN
		,A.MQSOFT
		,MM.MMDCCD
		,MM.MMITDS
		,A.MQTRQT
		,A.MQALQT
		,G2STAT,G2ALQT,G2MSLN
		,ML.STQT,ML.ALQT
	ORDER BY 
	coalesce(G2STAT,0) asc,
	A.MQITNO
		,A.MQSOFT DESC
		,A.MQALQT