/* do not change the next line, which is the DataSource: 
Movex Java
*/ 

	SELECT VARCHAR_FORMAT(T.WHS_CUR_TIME, 'YYYYMMDD') AS DT
		,VARCHAR_FORMAT(T.WHS_CUR_TIME, 'HH24MIss') AS TM
	FROM (
		SELECT CURRENT TIMESTAMP + cast(cast(TZ.TZTGMT - (
						SELECT SY.TZTGMT
						FROM ##CITZON## SY
						WHERE SY.TZCONO = TZ.TZCONO
							AND SY.TZYEA4 = TZ.TZYEA4
							AND SY.TZTIZO = '&SYS'
						) AS NUMERIC(3, 0)) / 100 AS NUMERIC(2, 0)) hours AS WHS_CUR_TIME
		FROM ##CSYTAB##
		JOIN ##CITZON## TZ ON TZ.TZCONO = CTCONO
			AND TZ.TZTIZO = substring(CTPARM, 16, 4)
		JOIN ##MITWHL## ON MWCONO = CTCONO
			AND MWSDES = CTSTKY
		WHERE CTCONO = %cono%
			AND CTSTCO = 'EDES'
			AND MWWHLO = '%whlo%'
			AND TZ.TZYEA4 = YEAR(CURRENT DATE)
		) AS T
